### ISSUE TITLE
Convert existing word doc to markdown

### ISSUE THREAD

**Issue by drnikki** [drupaldiversity/event-organizer-packet#1]

**Comment by cleverington** [comment]
## Submitted
90093b6bb773ccac9b09016f567e10bb1797dac3

Document converted, but needs to be split into sections.

**Comment by drnikki** [comment]
@cleverington did you use Gitbook to edit this or another tool? Want to make sure I'm using the same toolchain as you for updates.  my local gitbook instance is being wonky.

**Comment by cleverington** [comment]
@drnikki Honestly, I've just been hardcoding it. I've played in Markdown for years.

What is it doing wrong? Its possible I used a dated version of the T.O.C. generation which may have caused your issue?  

What is it doing wrong?

Worst case scenario, I can add your account to where I have it published on GitBooks.io and you can edit it 'in-page' using the built-in Editor.

**Comment by drnikki** [comment]
@cleverington it's not doing anything wrong. I just assumed that you'd used the gitbooks editor to generate and arrange things and they don't really play nicely.  I'm fine with handcoding it in markdown. :)

**Comment by cleverington** [comment]
@drnikki This issue can probably be closed out as well.
