### ISSUE TITLE
gitbook!

### ISSUE THREAD

**Issue by drnikki** [drupaldiversity/event-organizer-packet#4]
@cleverington 
An organization exists at gitbook - https://www.gitbook.com/@drupal-diversity

It syncs with github so membership should also sync there as well.  What else should I do for this?

**Comment by cleverington** [comment]
@drnikki Sweet! Once it has me as a member, we'll push the packet out!

**Comment by drnikki** [comment]
Shoudl be good now - I added you manually to that org and confirmed that it's set to 'sync with github'

**Comment by cleverington** [comment]
@drnikki May I cheerfully recommend closing the issue! We are LIVE BABY!

https://www.gitbook.com/book/drupal-diversity/drupal-organizer-resources/details

**Comment by drnikki** [comment]
HOORAY
