### ISSUE TITLE
Inclusion Strategies

### ISSUE THREAD

**Issue by drnikki** [drupaldiversity/event-organizer-packet#8]
https://drupal-diversity.gitbooks.io/drupal-organizer-resources/content/manuscript/diversity-inclusion-strategies/diversity-inclusion-strategies.html

We need to provide a list of specific, actionable things that organizers can do to be more inclusive.  We want to include actions at all levels of difficulty and cost, but keep in mind that the target audience here is small, local camp organizers who are likely underresourced and understaffed. 

An ideal format may be:

- introduction paragraph for why this list is here
- actions that take 5 minutes
- actions that take 10 minutes
- actions that are quick but cost $
(etc. etc.)

**Comment by Cottser** [comment]
- Make the organizing team as diverse as possible (almost step zero? maybe this fits better somewhere else but it does seem important to me)
- Provide live captioning
- Provide gender friendly (neutral?) bathrooms
- Provide food that works for different dietary, religious, etc. needs
- …etc, those are just some random ones that came to mind.

**Comment by drnikki** [comment]
@Cottser think I got all of your recommendations in the PR, but please edit/comment as you see fit.

**Comment by drnikki** [comment]
Going to close this as the first-pass ticket that it is.  We'll open others as we revise.
